---
on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: terraform
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: custom
          - name: default
          - name: no_public_ip
          - name: subnet
          - name: volume
      max-parallel: 3
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "./examples/${{ matrix.config.name }}/prerequisites"
      - name: terraform prerequisites init
        uses: robertdebock/terraform-action@1.1.2
        with:
          directory: ./examples//${{ matrix.config.name }}/prerequisites  
        if: steps.check_files.outputs.files_exists == 'true'
      - name: terraform prerequisites apply
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: apply
          directory: ./examples//${{ matrix.config.name }}/prerequisites
        env:
          TF_CLI_ARGS: "-input=false -auto-approve"
        if: steps.check_files.outputs.files_exists == 'true'
      - name: terraform init
        uses: robertdebock/terraform-action@1.1.2
        with:
          directory: ./examples/${{ matrix.config.name }}
      - name: terraform validate
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: validate
          directory: ./examples/${{ matrix.config.name }}
      - name: terraform plan
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: plan
          directory: ./examples/${{ matrix.config.name }}
      - name: terraform apply
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: apply
          directory: ./examples/${{ matrix.config.name }}
        env:
          TF_CLI_ARGS: "-input=false -auto-approve"
      - name: terraform destroy
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: destroy
          directory: ./examples/${{ matrix.config.name }}
        env:
          TF_CLI_ARGS: "-input=false -auto-approve"
        if: ${{ always() }}
      - name: terraform prerequisites destroy
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: destroy
          directory: ./examples//${{ matrix.config.name }}/prerequisites
        env:
          TF_CLI_ARGS: "-input=false -auto-approve"
        if: steps.check_files.outputs.files_exists == 'true'

